# Generated by Django 4.2.6 on 2023-10-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance  ', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='data',
            new_name='date',
        ),
    ]
