# Generated by Django 4.2.5 on 2023-11-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attendance_options_rename_data_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=70),
        ),
    ]
